elastic:
  enterprise_search:
    url: 'http://host.docker.internal:3200'
    access_token: 'changeme'
  apm:
    enabled: false
    url: 'http://host.docker.internal:8200'
    secret_token: 'changeme'
