elastic:
  enterprise_search:
    host: 'http://host.docker.internal:3002'
    username: 'elastic'
    password: 'changeme'
  apm:
    enabled: false
    host: 'host.docker.internal:8200'
    secret_token: 'changeme'
