filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['host.docker.internal:9200']
  username: 'elastic'
  password: 'changeme'
filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /source_logs/*
